//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtTypeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtType
    {
        public byte Id { get; set; }
        public string Type { get; set; }
        public float Price { get; set; }
    }
}
